### ISSUE TITLE
[EL-PRO]基本設計-画面レイアウト仕様書 

### ISSUE THREAD

**Issue by ebforlearng1java** [ebforlearng1java/EL-PRO#1]
## テンプレート
[画面レイアウト仕様書_テンプレート.xlsx](https://github.com/ebforlearng1java/EBPro_G2/files/8423882/_.xlsx)

## 修正コメント
例）　【仕様変更】テスト一覧画面の追加 EB李 20220407

**Comment by ebforlearng1java** [comment]
![１２３](https://user-images.githubusercontent.com/69588837/161975885-e6731c63-e7f7-4012-a20d-32b87d5cf394.jpg)

**Comment by ebforlearng1java** [comment]
[220406　銭米茄.xlsx](https://github.com/ebforlearng1java/EBPro_G2/files/8425221/220406.xlsx)

**Comment by Kin365** [comment]
[220407_Kin.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8431191/220407_Kin.xlsx)

**Comment by tudou1213** [comment]
[画面レイアウト仕様書WANG XINYUE.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8438809/WANG.XINYUE.xlsx)

**Comment by Faonzei** [comment]
[画面レイアウト仕様書(方).xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8439188/default.xlsx)

**Comment by OliveSya** [comment]
[220407 王利鋒.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8439194/220407.xlsx)

**Comment by musu-tuomo** [comment]
[220406_musu_tuomo.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8439197/220406_musu_tuomo.xlsx)

**Comment by yamazoeshun** [comment]
[EB_4.26_山添.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8439209/EB_4.26_.xlsx)

**Comment by yamazoeshun** [comment]
[ELPRO仕様書4.08_山添.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8448096/ELPRO.4.08_.xlsx)

**Comment by tudou1213** [comment]
>

**Comment by tudou1213** [comment]
[画面レイアウト仕様書WANG XINYUE修正.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8448104/WANG.XINYUE.xlsx)

**Comment by tudou1213** [comment]
[画面レイアウト仕様書WANG XINYUE修正.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8448596/WANG.XINYUE.xlsx)

**Comment by OliveSya** [comment]
[220408 王利鋒.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8448666/220408.xlsx)

**Comment by Kin365** [comment]
[220408_LAYOUT_Kin.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8448690/220408_LAYOUT_Kin.xlsx)

**Comment by miga1120** [comment]
[220408　銭米茄　画面レイアウト仕様書　修正.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8448764/220408.xlsx)

**Comment by musu-tuomo** [comment]
【仕様変更】テスト一覧画面シート追加，各種ボタン修正．EB 拇速 2022/04/08 ．

**Comment by musu-tuomo** [comment]
【仕様変更】テスト一覧画面シート追加，各種ボタン修正．EB 拇速 2022/04/08.
[220406_musu_tuomo.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8448812/220406_musu_tuomo.xlsx)

**Comment by yamazoeshun** [comment]
[[EL-PRO]画面レイアウト仕様書_山添_0408_1.2版.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8448995/EL-PRO._._0408_1.2.xlsx)

**Comment by Kin365** [comment]
[【EL-PRO】画面レイアウト仕様書_Kin_20220412_1.3版.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8470765/EL-PRO._Kin_20220412_1.3.xlsx)

**Comment by OliveSya** [comment]
[[EL_PRO]プレイアウト仕様書_WANG LIFENG_20220408_1.2版.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8470889/EL_PRO._WANG.LIFENG_20220408_1.2.xlsx)

**Comment by musu-tuomo** [comment]
[[EL_PRO] 画面レイアウト仕様書_musu_220408_ver_1.3.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8487249/EL_PRO._musu_220408_ver_1.3.xlsx)
