### ISSUE TITLE
仕様書整理　[EL-PRO]基本設計-画面遷移図

### ISSUE THREAD

**Issue by ebforlearng1java** [ebforlearng1java/EL-PRO#18]

**Comment by Faonzei** [comment]
[【EL-PRO】基本設計ー画面遷移図.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8529324/EL-PRO.xlsx)

**Comment by ebforlearng1java** [comment]
## レビュー指摘　
4/25
[指摘管理表_【EL-PRO】基本設計-画面遷移図.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8551753/_.EL-PRO.-.xlsx)

**Comment by Faonzei** [comment]
[【EL-PRO】基本設計ー画面遷移図_20220426.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8559541/EL-PRO._20220426.xlsx)
[指摘管理表_【EL-PRO】基本設計-画面遷移図.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8559542/_.EL-PRO.-.xlsx)
