### ISSUE TITLE
仕様書整理　[EL-PRO]基本設計-画面一覧

### ISSUE THREAD

**Issue by ebforlearng1java** [ebforlearng1java/EL-PRO#19]

**Comment by musu-tuomo** [comment]
[[EL_PRO] 画面一覧表_musu_220408_ver1.1.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8568378/EL_PRO._musu_220408_ver1.1.xlsx)

**Comment by ebforlearng1java** [comment]
## レビュー指摘
4/27
①　正式納品向けの初期作成のため、履歴情報シートにバージョンアップしないでください。
②　画面一覧表シート　：　画面IDのネーミングルールがあるため、下記ご参照ください。
　https://github.com/ebforlearng1java/EL-PRO/issues/7
　
③　画面一覧表シート　：　画面名称を左寄せにしてください
④　画面一覧表シート　：　画面名称に画面レイアウト仕様書と一致しないとNGです。
⑤　画面一覧表シート　：　機能にもっと詳しくて記載してください。
⑥　全ブック：作成日付が不正

**Comment by musu-tuomo** [comment]
修正版です。
[【EL-PRO】 基本設計-画面一覧仕様書.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8569017/EL-PRO.-.xlsx)

**Comment by ebforlearng1java** [comment]
## レビューOK
