### ISSUE TITLE
仕様書整理　[EL-PRO]基本設計-ER図

### ISSUE THREAD

**Issue by ebforlearng1java** [ebforlearng1java/EL-PRO#20]

**Comment by tudou1213** [comment]
[[ER-PRO]基本設計-ER図.puml.txt](https://github.com/ebforlearng1java/EL-PRO/files/8553111/ER-PRO.-ER.puml.txt)

**Comment by ebforlearng1java** [comment]
## レビュー指摘
4/26

指摘なし

**Comment by ebforlearng1java** [comment]
## No1 不具合対応
修正後ファイル

**Comment by ebforlearng1java** [comment]
## テーブル定義書の指摘より基本設計書修正
修正後ファイル

**Comment by ebforlearng1java** [comment]
>①exam_eventテーブルのPK変更
>　test_datatime　→　exam_event_id
→上記の通りに対応しました。


>②exam_eventのtest_idをFKにする


>③user_test_answerのPKを複数化にする
　・exam_event_id
　・question_id
>④creat_datetimeの誤字
>⑤user_test_answerテーブルに　回答状態の項目を追加
　answer_right_or_wrong
>⑥questionテーブルに　正しく選択枝の数を追加
option_count 　→　right_select_count ( int 　1:ラジオ　2以上：チェックボックス)

>⑦　questionテーブルのPKにtest_idを追加
　　optionテーブルのPKにtest_id、question_idを追加
>⑧　optionテーブルのoption_title項目を削除
