### ISSUE TITLE
[EL-PRO]詳細設計-画面制御仕様書-表示非表示の作成

### ISSUE THREAD

**Issue by ebforlearng1java** [ebforlearng1java/EL-PRO#21]

**Comment by yamazoeshun** [comment]
[【EL-PRO】詳細設計-画面制御仕様書-表示非表示.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8561019/EL-PRO.-.-.xlsx)

**Comment by ebforlearng1java** [comment]
## レビュー指摘
①　登録画面の2パターン構造が必要
 　　・新規登録
 　　・会員情報修正

**Comment by yamazoeshun** [comment]
[【EL-PRO】詳細設計-画面制御仕様書-表示非表示.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8569978/EL-PRO.-.-.xlsx)

**Comment by ebforlearng1java** [comment]
## レビュー指摘
①　登録画面のmail項目の表示非表示制御を削除
②　テスト画面のテストコードステータスに下記の通りに変更
　「テストコードが非表示」
③　テスト画面：オプションセットステータ　→　ステータオプションセット
④　間違った問題：　セル赤反転に修正してください

**Comment by yamazoeshun** [comment]
[【EL-PRO】詳細設計-画面制御仕様書-表示非表示.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8579005/EL-PRO.-.-.xlsx)

**Comment by ebforlearng1java** [comment]
## レビューOK
