### ISSUE TITLE
[EL-PRO]詳細設計-テーブル定義書の作成

### ISSUE THREAD

**Issue by tudou1213** [ebforlearng1java/EL-PRO#22]

**Comment by OliveSya** [comment]
[【ER-PRO】詳細設計-テーブル定義書.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8560106/ER-PRO.-.xlsx)

**Comment by ebforlearng1java** [comment]
## レビュー指摘
4/26
[指摘管理表_【EL-PRO】詳細設計-テーブル定義書.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8560244/_.EL-PRO.-.xlsx)

**Comment by tudou1213** [comment]
## レビュー指摘対応
4/26
### 仕様書
[【EL-PRO】詳細設計-テーブル定義書.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8561070/EL-PRO.-.xlsx)


### 指摘管理表
[指摘管理表_【EL-PRO】詳細設計-テーブル定義書.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8561081/_.EL-PRO.-.xlsx)

**Comment by ebforlearng1java** [comment]
## レビューOK

**Comment by OliveSya** [comment]
## 不具合対応
修正後ファイル
[【EL-PRO】詳細設計-テーブル定義書.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8569136/EL-PRO.-.xlsx)
