### ISSUE TITLE
[EL-PRO]詳細設計-画面項目定義書-ログイン画面

### ISSUE THREAD

**Issue by miga1120** [ebforlearng1java/EL-PRO#23]

**Comment by miga1120** [comment]
[[EL-PRO]詳細設計-画面項目定義書-ログイン画面.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8561258/EL-PRO.-.-.xlsx)

**Comment by ebforlearng1java** [comment]
## レビュー指摘
①　エラーメッセージ表示エリア項目の追加

**Comment by miga1120** [comment]
###レビュー指摘対応
①上記の通りに、エラーメッセージ表示エリア項目を追加しました。
[[EL-PRO]詳細設計-画面項目定義書-ログイン画面.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8569914/EL-PRO.-.-.xlsx)

**Comment by ebforlearng1java** [comment]
## レビューOK
