### ISSUE TITLE
[EL-PRO]詳細設計-画面項目定義書-パスワード変更

### ISSUE THREAD

**Issue by miga1120** [ebforlearng1java/EL-PRO#24]

**Comment by miga1120** [comment]
[[EL-PRO]詳細設計-画面項目定義書-パスワード変更.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8579227/EL-PRO.-.-.xlsx)

**Comment by miga1120** [comment]
[【EL-PRO】詳細設計_画面項目定義書_パスワード変更.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8580169/EL-PRO._._.xlsx)

## レビュー指摘対応
①　登録画面の指摘を展開してください。
→ 上記の通りに、対応しました。

・「EL-PRO」詳細設計-画面項目定義書-パスワード変更画面.xlsx
→【EL-PRO】詳細設計_画面項目定義書_パスワード変更画面.xlsx
・ページプレビューの範囲を直しました。
・エラーの項目名称と記号を変更しました。
・タイトル系の項目をlblからtblに変更しました。

**Comment by ebforlearng1java** [comment]
## レビューOK
