### ISSUE TITLE
[EL-PRO]詳細設計-画面項目定義書-登録画面

### ISSUE THREAD

**Issue by miga1120** [ebforlearng1java/EL-PRO#25]

**Comment by miga1120** [comment]
[[EL-PRO]詳細設計-画面項目定義書-登録画面.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8579131/EL-PRO.-.-.xlsx)

**Comment by miga1120** [comment]
[【EL-PRO】詳細設計_画面項目定義書_登録画面.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8580128/EL-PRO._._.xlsx)

## レビュー指摘対応
①　ファイル名称に中括弧[]が含まれた場合に、windowsで開けないため、
　　下記の通りにファイル名称を見直して下さい。

→ 上記の通りに、対応しました。
　「EL-PRO」詳細設計-画面項目定義書-登録画面.xlsx
→【EL-PRO】詳細設計_画面項目定義書_登録画面.xlsx

②改ページプレビューの範囲を見直して下さい。

→ 上記の通りに、ページプレビューの範囲を直しました。

③　性別の選択枝に対して、下記の通りにセットに設定したほうがよい

→ 上記の通りに、対応しました。
　男性→男性_タイトル、sel→lbl、表示文字→固定文字
　男性：rdo列を追加しました。
　　※３つ選択枝は同じです。

④　エラーメッセージ：errormessage
　　項目名称と記号が重複不可のため、XXXX項目_エラーメッセージ　に変更してください
→ 上記の通りに、エラーの項目名称と記号を変更しました。

⑤　パスワード_タイトル　に④の指摘も対応してください
→ 上記の通りに、パスワード再入力の項目名称と記号を変更しました。

⑥　title系（固定文字系）の項目に対して、lbl ⇒ tblにしてください。
→ 上記の通りに、タイトル系の項目をlblからtblに変更しました。

**Comment by ebforlearng1java** [comment]
## レビューOK
