### ISSUE TITLE
[EL-PRO]詳細設計-画面項目定義書-得点画面

### ISSUE THREAD

**Issue by Faonzei** [ebforlearng1java/EL-PRO#28]

**Comment by Faonzei** [comment]
[【EL-PRO】詳細設計-画面項目定義書-得点画面.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8579063/EL-PRO.-.-.xlsx)

**Comment by Faonzei** [comment]
[【EL-PRO】詳細設計-画面項目定義書-得点画面.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8579572/EL-PRO.-.-.xlsx)

## 指摘対応

> ①　敬称に固定文字「さん」　⇒「様」に変更したほうがよい
＝＞　指摘の通り、修正しました。

> ②　下記項目に対して、一つ統合したほうがよい
> 　　初回の一言＿合格、初回の一言＿失敗　
> 　　試験状態＿合格、試験状態＿失敗
＝＞　指摘の通り、修正しました。

> ③　繰り返し部分　＃START　＊ｘは問題番号　ｙは回答番号
> 　　⇒　1行の場合は、yが不要だと思います。
＝＞　yを削除して、項目企業を「result_x」に変更しました。

> ④　回答集計（複数）のタイプを「div」⇒「lbl」に変更したほうがよい
＝＞　指摘の通り、修正しました。

**Comment by ebforlearng1java** [comment]
## レビューOK
