### ISSUE TITLE
[EL-PRO]詳細設計-メッセージ定義書(フロントエンドシート)

### ISSUE THREAD

**Issue by yamazoeshun** [ebforlearng1java/EL-PRO#32]
- [] #12

**Comment by yamazoeshun** [comment]
- [] #12 
- [] #16

**Comment by yamazoeshun** [comment]
[【EL-PRO】詳細設計-メッセージ定義書-フロントエンド.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8569864/EL-PRO.-.-.xlsx)

**Comment by yamazoeshun** [comment]
[【EL-PRO】詳細設計-メッセージ定義書-フロントエンド.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8570028/EL-PRO.-.-.xlsx)

**Comment by ebforlearng1java** [comment]
## レビュー指摘
①クライアント(フロントエンド)シート　：　　ユーザー名および「▼」を押下した場合　のエラーコードを削除
②　パスワード変更画面：パスワード再入力がパスワードと一致しない場合　のチェックを追加

**Comment by yamazoeshun** [comment]
[【EL-PRO】詳細設計-メッセージ定義書-フロントエンド.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8579042/EL-PRO.-.-.xlsx)

**Comment by ebforlearng1java** [comment]
## レビューOK
