### ISSUE TITLE
[EL-PRO]詳細設計-メッセージ定義書(バックエンドシート)

### ISSUE THREAD

**Issue by ebforlearng1java** [ebforlearng1java/EL-PRO#33]

**Comment by musu-tuomo** [comment]
https://docs.google.com/file/d/1YvJ00-IK-z5TB3DR75S06ajh7QN0m0C_/edit?usp=docslist_api&filetype=msexcel

**Comment by ebforlearng1java** [comment]
[【EL-PRO】詳細設計-メッセージ定義書-バックエンド.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8579658/EL-PRO.-.-.xlsx)

**Comment by ebforlearng1java** [comment]
## レビューOK
