### ISSUE TITLE
[EL-PRO]基本設計-ER図

### ISSUE THREAD

**Issue by ebforlearng1java** [ebforlearng1java/EL-PRO#4]
### PlantUML 
[PlantUML版のテンプレート_[ER-PRO]基本設計-ER図_李_20220419_1.1.puml.txt](https://github.com/ebforlearng1java/EL-PRO/files/8510148/PlantUML._.ER-PRO.-ER._._20220419_1.1.puml.txt)

### Excel
[Excel版のテンプレート_[ER-PRO]基本設計-ER図_李_20220419_1.1.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8510149/Excel._.ER-PRO.-ER._._20220419_1.1.xlsx)

**Comment by Faonzei** [comment]
[【ER-PRO】基本設計ーER図_方_20220418_1.1.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8504468/ER-PRO.ER._._20220418_1.1.xlsx)

**Comment by tudou1213** [comment]
[Excel版のテンプレート[ER-PRO]基本設計-ER図_王（欣）_20220414_1.0.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8504669/Excel.ER-PRO.-ER._._20220414_1.0.xlsx)

**Comment by OliveSya** [comment]
[[EL_PRO]基本設計ーER図_WANGLIFENG_20220418_1.0.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8505960/EL_PRO.ER._WANGLIFENG_20220414_1.0.xlsx)

**Comment by yamazoeshun** [comment]
[【EL-PRO】基本設計-ER図_山添_20220418_1.1.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8506414/EL-PRO.-ER._._20220418_1.1.xlsx)

**Comment by miga1120** [comment]
[[ER-PRO]基本設計ER図_銭_20220419_1.1.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8508849/ER-PRO.ER._._20220419_1.1.xlsx)

**Comment by Kin365** [comment]
[【EL-PRO】ER図_Kin_20220419_1.1版.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8509049/EL-PRO.ER._Kin_20220419_1.1.xlsx)

**Comment by yamazoeshun** [comment]
Excel

[【EL-PRO】基本設計-ER図_山添_20220419_1.2.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8511240/EL-PRO.-ER._._20220419_1.2.xlsx)

PlantUML
[PlantUML版のテンプレート_[ER-PRO]基本設計-ER図_山添_20220419_1.2.txt](https://github.com/ebforlearng1java/EL-PRO/files/8511244/PlantUML._.ER-PRO.-ER._._20220419_1.2.txt)
