### ISSUE TITLE
[EL-PRO]基本設計-画面一覧

### ISSUE THREAD

**Issue by ebforlearng1java** [ebforlearng1java/EL-PRO#5]

**Comment by yamazoeshun** [comment]
[ELPRO仕様書4.08_山添.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8447909/ELPRO.4.08_.xlsx)

**Comment by tudou1213** [comment]
[画面一覧.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8448703/default.xlsx)

**Comment by miga1120** [comment]
[220408　銭米茄　画面一覧表.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8448762/220408.xlsx)

**Comment by Faonzei** [comment]
[【EL-PRO】画面一覧_方_20220408.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8448959/EL-PRO._._20220408.xlsx)

**Comment by yamazoeshun** [comment]
[[EL-PRO]画面一覧仕様書_山添_0408_1.2版.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8449003/EL-PRO._._0408_1.2.xlsx)

**Comment by OliveSya** [comment]
[[EL_PRO]画面一覧仕様書_WANG_20220408.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8449281/EL_PRO._WANG_20220408.xlsx)

**Comment by musu-tuomo** [comment]
[220408_musu_tuomo_gamenichiran.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8449355/220408_musu_tuomo_gamenichiran.xlsx)

**Comment by musu-tuomo** [comment]
[[EL_PRO]画面一覧仕様書_musu_220408_ver1.2.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8449477/EL_PRO._musu_220408_ver1.2.xlsx)

**Comment by Kin365** [comment]
[【EL-PRO】画面一覧仕様書_金_20220408_1.0版.xlsx](https://github.com/ebforlearng1java/EL-PRO/files/8449756/EL-PRO._._20220408_1.0.xlsx)
